name: Elijah Hauber
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# Performance optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]

# Plugins for performance
plugins:
  - jekyll-sitemap
  - jekyll-compress-images
  - jekyll-minifier

# Image optimization
compress_images:
  images_path: "assets/**/*.{gif,png,jpg,jpeg,svg}"

# Sass configuration for CSS optimization
sass:
  style: compressed
  sourcemap: never

# Exclude unnecessary files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
